server:
  port: 8001

spring:
  application:
    name: userService  # 服务名（重点！）
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # 注册到Nacos
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true