server:
  port: 8002

spring:
  application:
    name: orderService
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # Nacos

  # 👇 下面这些直接追加在后面就行
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect